Add listening ports as argument
projectdiscovery/interactsh pull request #128
Opened 2021-12-15 16:32 UTC by kalidor

I needed to pass listening ports as argument to be more flexible.
One of the main difference is the use of "fmt.Sprintf" function...
This is my first PR, don't hesitate if you have any remarks/comment/whatever :)
This closes #113

2021-12-16 22:24 UTC, Mzack9999 requested changes
Great work! If you could rename the variable name and CLI argument, the PR is ready to be merged. Thanks!

2021-12-16 22:24 UTC, Mzack9999 commented on cmd/interactsh-server/main.go
> +	flag.IntVar(&options.DomainPort, "domain-port", 53, "Port to use by DNS server for interactsh server")
could you please rename this `dns-port` and `options.DnsPort`?

2021-12-17 17:30 UTC, kalidor commented
I just did. Just for the record, this PR don't change a thing in responder docker behavior.

2021-12-17 20:56 UTC, Mzack9999 approved these changes

2021-12-19 16:51 UTC, ehsandeep approved these changes

2021-12-19 16:51 UTC, merged