Accurately list listening services
projectdiscovery/interactsh pull request #130
Opened 2021-12-15 23:54 UTC by AV-IO

The following commits enable interactsh to:

- more consistently log
  - using gologger instead of a combination of gologger, fmt, and log
- accurately list listening services
  - before this change, the server will always state that it is "Listening on DNS, SMTP and HTTP ports" even if those services have failed or more services are being used.
  - with the use of channels, each of the "ListenAndServe" goroutines can communicate to the main goroutine:
    - when they are starting
    - in case they fail or error, stop the server instead of failing silently

2021-12-16 22:14 UTC, Mzack9999 requested changes
Great work! Everything looks good, but I think we need to remove the following line from `interactsh/cmd/interactsh-server/main.go`:

```
gologger.DefaultLogger.SetWriter(&noopWriter{})
```

otherwise gologger output is not shown:
```
$ cd interactsh/cmd/interactsh-server/
$ go run .
exit status 1
```

2021-12-17 21:01 UTC, Mzack9999 approved these changes

2021-12-19 16:55 UTC, ehsandeep requested changes
@AV-IO could you please rebase this PR with the dev branch? thanks again.

2021-12-19 17:43 UTC, AV-IO commented
Done!
Sorry for the delay.

2021-12-20 11:01 UTC, Mzack9999 approved these changes

2021-12-20 14:14 UTC, merged