Implement IPv6 support for DNS, fix some DNS server behaviours
projectdiscovery/interactsh pull request #186
Opened 2022-01-14 00:45 UTC by fincham

This commit allows the DNS server to serve IPv6 address records (AAAA) for both interaction and NS glue. In combination with the changes in #181 and #182 this allows for IPv6 interaction and provides more opportunities for interaction to ocurr when e.g. IPv6 and IPv4 egress firewalling differ on a network being tested.

Specifying the '-ip' option multiple times now allows setting multiple response addresses for the DNS server. Both IPv4 and IPv6 addresses are supported. If no IP address is specified the auto-detected address will be logged at startup time to aid with troubleshooting.

Fixes a couple of behaviour bugs with the DNS server implementation and changes the default TTL to `5` from `3600`.

2022-01-14 07:55 UTC, fincham commented
I should say as well: this is a fairly big diff and I'm certainly open to revising it if it isn't in line with your plans for things.

2022-02-10 10:58 UTC, ehsandeep requested changes
Code conflict

2022-06-20 03:43 UTC, pulse-michaelfincham commented
Hi folks,

I'm going to look at re-writing this patch and will re-submit it against current dev.

Cheers,
Michael

2022-06-20 10:37 UTC, ehsandeep commented
@pulse-michaelfincham thank you 🙌🏻  It would be great if you could split the PR into multiple, each with a particular change.

2022-06-20 10:58 UTC, ehsandeep commented
@pulse-michaelfincham I created #307 for one of the features introduced in this, and I intended to do the same for two other changes made in this PR, but I don't have enough context, so I'll leave it up to you to put it in the PR or issue.

Thanks again, closing this PR now as this will be handled separately.

2022-06-20 10:58 UTC, closed without merging