Adding Multi-Domain support
projectdiscovery/interactsh pull request #286
Opened 2022-05-10 11:13 UTC by Mzack9999

## Description
This PR adds multi-domain support in `interactsh-server`

2022-05-15 17:34 UTC, ehsandeep requested changes
-  [x] Failed to load/read newly created ssl certificate upon 1st run
<details>
<summary>Issue detail</summary>

```bash
# make sure to delete /root/.local/share/certmagic directory first to reproduce this
# first run

go run . -d hackwithautomation.com -d cves.sh

    _       __                       __       __  
   (_)___  / /____  _________ ______/ /______/ /_ 
  / / __ \/ __/ _ \/ ___/ __ '/ ___/ __/ ___/ __ \
 / / / / / /_/  __/ /  / /_/ / /__/ /_(__  ) / / /
/_/_/ /_/\__/\___/_/   \__,_/\___/\__/____/_/ /_/ 1.0.4

                projectdiscovery.io

[INF] Requesting SSL Certificate for:  [*.hackwithautomation.com, hackwithautomation.com]
[INF] Successfully Created SSL Certificate at: /root/.local/share/certmagic
[ERR] An error occurred while applying for an certificate, error: open /root/.local/share/certmagic/certificates/acme-v02.api.letsencrypt.org-directory/hackwithautomation.com/hackwithautomation.com.crt: no such file or directory
[ERR] Could not generate certs for auto TLS, https will be disabled
[INF] Requesting SSL Certificate for:  [*.cves.sh, cves.sh]
[INF] Successfully Created SSL Certificate at: /root/.local/share/certmagic
[ERR] An error occurred while applying for an certificate, error: open /root/.local/share/certmagic/certificates/acme-v02.api.letsencrypt.org-directory/cves.sh/cves.sh.crt: no such file or directory
[ERR] Could not generate certs for auto TLS, https will be disabled
[INF] Listening with the following services:
[DNS] Listening on TCP 157.230.223.165:53
[SMTP] Listening on TCP 157.230.223.165:25
[HTTPS] Listening on TCP 157.230.223.165:443
[SMTPS] Listening on TCP 157.230.223.165:587
[DNS] Listening on UDP 157.230.223.165:53
[HTTP] Listening on TCP 157.230.223.165:80
[LDAP] Listening on TCP 157.230.223.165:389
[ERR] Could not serve http on tls: open : no such file or directory
```

```bash
# 2nd run

go run . -d hackwithautomation.com -d cves.sh

    _       __                       __       __  
   (_)___  / /____  _________ ______/ /______/ /_ 
  / / __ \/ __/ _ \/ ___/ __ '/ ___/ __/ ___/ __ \
 / / / / / /_/  __/ /  / /_/ / /__/ /_(__  ) / / /
/_/_/ /_/\__/\___/_/   \__,_/\___/\__/____/_/ /_/ 1.0.4

                projectdiscovery.io

[INF] Loading existing SSL Certificate for:  [*.hackwithautomation.com, hackwithautomation.com]
[INF] Loading existing SSL Certificate for:  [*.cves.sh, cves.sh]
[INF] Listening with the following services:
[SMTP] Listening on TCP 157.230.223.165:25
[DNS] Listening on TCP 157.230.223.165:53
[HTTPS] Listening on TCP 157.230.223.165:443
[SMTPS] Listening on TCP 157.230.223.165:587
[DNS] Listening on UDP 157.230.223.165:53
[HTTP] Listening on TCP 157.230.223.165:80
[LDAP] Listening on TCP 157.230.223.165:389

```
</details>

- [ ] domain name banner fix

<img width="472" alt="image" src="https://user-images.githubusercontent.com/8293321/168486035-11a2ba42-0c03-4d9e-8d58-52543eeb3187.png">

currently, the first domain name gets included in other server index pages as well.

- [x] comma separated domain name input support

```
go run . -d hackwithautomation.com,cves.sh
```

2022-05-16 12:45 UTC, Ice3man543 commented on pkg/server/dns_server.go
> +		dotDomains := []string{zone, dns.Fqdn(h.options.Domains[0])}
Why are we using zone and the first domain specified by user during result creation? Ideally, won't we only want to use the domain received in the interaction?

2022-05-16 13:19 UTC, Mzack9999 commented on pkg/server/dns_server.go
> +		dotDomains := []string{zone, dns.Fqdn(h.options.Domains[0])}
If the `zone` provided is not found within the map containing the corresponding ns servers, we fall back to the first configured domain, as it happens now with hardcoded default ns records.

2022-05-19 10:33 UTC, ehsandeep approved these changes

2022-05-22 06:21 UTC, Ice3man543 approved these changes

2022-05-22 08:46 UTC, merged