Added static file and directory server
projectdiscovery/interactsh pull request #332
Opened 2022-07-16 08:35 UTC by Ice3man543

Closes #320

2022-07-16 11:15 UTC, ehsandeep requested changes
- [x] Bug: custom banner/index also overwrite expected response of payload
<img width="705" alt="image" src="https://user-images.githubusercontent.com/8293321/179352308-a214e8c3-e79b-4430-a8e5-b8b82b4ba3bf.png">

- [ ] Update: disable directory listing

<img width="391" alt="image" src="https://user-images.githubusercontent.com/8293321/179352483-0ee35eab-74bd-4fa8-ace6-e8c11b54ad43.png">

2022-07-16 11:32 UTC, ehsandeep requested changes
- [ ] Update: adding logging when options used

```console
[INF] Loading existing SSL Certificate for:  [*.hackwithautomation.com, hackwithautomation.com]
[INF] Loading directory (/User/xxx/) to serve from : hackwithautomation.com/s/
[INF] Using custom server index:  /User/xxx/xxx/banner.html
```

- [ ] update: adding project version in response header (`x-interactsh-version`)

```console
accept-ranges: bytes
content-type: text/javascript; charset=utf-8
last-modified: Tue, 05 Jul 2022 13:08:10 GMT
server: hackwithautomation.com
x-interactsh-version: 1.0.5
content-length: 2712
date: Sat, 16 Jul 2022 11:08:03 GMT
```

2022-07-16 14:53 UTC, Mzack9999 approved these changes
```console
$ curl http://localhost/s/
<pre>
<a href="Dockerfile">Dockerfile</a>
<a href="main.go">main.go</a>
<a href="smb_server.py">smb_server.py</a>
</pre>
```

2022-07-17 09:01 UTC, ehsandeep approved these changes

2022-07-17 09:09 UTC, merged