Export generated payload URLs to file
projectdiscovery/interactsh pull request #569
Opened 2023-05-24 08:25 UTC by dogancanbakir

Closes #518

2023-05-24 13:16 UTC, Mzack9999 requested changes
- [ ] Recommended minor changes
- [ ] Update `README.md`

2023-05-24 13:16 UTC, Mzack9999 commented on cmd/interactsh-client/main.go
> +		flagSet.StringVarP(&cliOptions.StorePayloadFile, "store-payload-file", "spf", "", "store generated interactsh payloads to output file"),
we can use a default filename like `interactsh_urls.txt`

2023-05-24 13:16 UTC, Mzack9999 commented on cmd/interactsh-client/main.go
> +		if _, err := storePayloadFile.WriteString(sb.String()); err != nil {
Probably `os.WriteFile` is shorter

2023-06-01 12:56 UTC, ehsandeep approved these changes

2023-06-01 12:57 UTC, merged